In [1]:
from desdeo_emo.surrogatemodels.EvoNN import EvoNN
from desdeo_emo.surrogatemodels.BioGP import BioGP
from desdeo_emo.surrogatemodels.EvoDN2 import EvoDN2
import numpy as np
import pandas as pd

from desdeo_emo.EAs import NSGAIII

# Generating Data

Make sure that the initial dataset is in a pandas dataframe

In [2]:
X = np.random.rand(100, 3)
y = X[:, 0] * X[:, 1] + X[:, 2]
y = y.reshape(-1, 1)
data = pd.DataFrame(np.hstack((X, y)), columns=["x1", "x2", "x3", "y"])

## EvoNN model

In [3]:
model = EvoNN(pop_size=100)
model.fit(data[["x1", "x2", "x3"]], data['y'])

Plot saved as:  EvoNN.html
View the plot by opening the file in browser.
To view the plot in Jupyter Notebook, use the IFrame command.


In [4]:
y_pred = model.predict(X)

In [5]:
model.performance

{'RMSE': 3.3297037246891223e-06,
 'R^2': 0.9999999998966824,
 'AICc': -2310.0254458989907}

In [6]:
model.predict([[0.1, 0.3, 0.5]])

(array([0.52999999]), array([0.]))

## BioGP model

In [7]:
model2 = BioGP(pop_size=50)
model2.fit(data[["x1", "x2", "x3"]], data['y'])

Plot saved as:  BioGP.html
View the plot by opening the file in browser.
To view the plot in Jupyter Notebook, use the IFrame command.


In [8]:
model2.performance

{'RMSE': 2.339714357336442e-16, 'R^2': 1.0}

In [9]:
model2.predict([[5,2,7]])

(array([17.]), array([0.]))

## EvoDN2 model

In [10]:
model3 = EvoDN2(training_algorithm=NSGAIII, pop_size=50)
model3.fit(data[["x1", "x2", "x3"]], data['y'])

E:\Projects\.virtualenvs\desdeo-emo\lib\site-packages\numpy\core\_asarray.py:102: VisibleDeprecationWarning:

Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.



Plot saved as:  EvoDN2.html
View the plot by opening the file in browser.
To view the plot in Jupyter Notebook, use the IFrame command.


In [11]:
model3.performance

{'RMSE': 0.00011249277455999585,
 'R^2': 0.9999998967122932,
 'Complexity': 1.134158614884136e-05}

In [12]:
model3.predict(np.asarray([[5,2,7]]))

array([[16.98876953]])